// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WeiHeMuStore.Model;

namespace WeiHeMuStore.Model.Migrations
{
    [DbContext(typeof(WeiHeMuStoreDBContext))]
    partial class WeiHeMuStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("WeiHeMuStore.Model.BaseModel.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IsHot");

                    b.Property<int?>("ProductCatesProductCateId");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(150);

                    b.Property<string>("ProductIntroduce")
                        .HasMaxLength(150);

                    b.Property<string>("ProductName")
                        .HasMaxLength(100);

                    b.Property<decimal>("ProductPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCatesProductCateId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WeiHeMuStore.Model.BaseModel.ProductCate", b =>
                {
                    b.Property<int>("ProductCateId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProductCateName")
                        .HasMaxLength(100);

                    b.HasKey("ProductCateId");

                    b.ToTable("ProductCates");
                });

            modelBuilder.Entity("WeiHeMuStore.Model.BaseModel.Product", b =>
                {
                    b.HasOne("WeiHeMuStore.Model.BaseModel.ProductCate", "ProductCates")
                        .WithMany("Products")
                        .HasForeignKey("ProductCatesProductCateId");
                });
#pragma warning restore 612, 618
        }
    }
}
